#define REDIS_GIT_SHA1 "319153fe"
#define REDIS_GIT_DIRTY "0"
#define REDIS_BUILD_ID "BHSU-1769609488"
#include "version.h"
#define REDIS_BUILD_ID_RAW REDIS_VERSION REDIS_BUILD_ID REDIS_GIT_DIRTY REDIS_GIT_SHA1
