#!/usr/bin/env python3
"""
Generate Coccinelle script with separate rules for each target function.
Removes 'static' keyword and extracts function declarations.

Usage: python3 2_4_extract_definition.py <json_file> <output_cocci>
"""

import json
import sys
import os

def load_target_functions(json_file):
    """Load target functions from filled_parsing JSON and extract unique assigned_fn."""
    with open(json_file, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    target_functions = set()
    
    # Handle both hashtable format (list) and filled_parsing format (dict)
    if isinstance(data, list):
        # Hashtable format: [{fp_name, assigned_fn}, ...]
        for entry in data:
            if 'assigned_fn' in entry and entry['assigned_fn']:
                for func in entry['assigned_fn']:
                    if isinstance(func, str) and func and func != "0":
                        target_functions.add(func)
    elif isinstance(data, dict):
        # filled_parsing format: {fp_name: [func1, func2, ...]}
        for fp_name, func_list in data.items():
            if isinstance(func_list, list):
                for func in func_list:
                    if isinstance(func, str) and func and func != "0":
                        target_functions.add(func)
    
    return sorted(target_functions)

def generate_header() -> str:
    """Generate the header with shared Python functions"""
    return """//
// Coccinelle script to remove 'static' keyword and extract function declarations
//
// Generated by: 2_4_extract_definition.py
// Purpose: Remove static from assigned_fn functions and extract declarations
//
// This script:
// 1. Removes the static keyword from function definitions and declarations
// 2. Extracts function signatures and prints them to stdout
//
// Usage: spatch --sp-file <output.cocci> --dir <source_directory> 2>/dev/null
//        (Redirects diff output to /dev/null, only declarations go to stdout)

// Shared Python functions
@initialize:python@
@@
import os
import re
import sys

def clean_function_signature(signature):
    '''Clean up function signature formatting'''
    if not signature:
        return signature
    
    # Normalize all whitespace
    signature = re.sub(r'\\s+', ' ', signature.strip())
    
    # Remove all spaces around asterisks first
    signature = re.sub(r'\\s*\\*\\s*', '*', signature)
    
    # Add space before asterisk groups
    signature = re.sub(r'(\\w)(\\*+)', r'\\1 \\2', signature)
    
    # Clean up double spaces
    signature = re.sub(r'\\s+', ' ', signature)
    
    return signature.strip()

def extract_and_print_signature(signature, func_name):
    '''Extract and print function signature to stdout'''
    clean_signature = clean_function_signature(signature)
    # Only print to stdout (will be captured by redirection)
    print(f"{clean_signature}")
    # Debug info goes to stderr
    print(f"[EXTRACTED] {func_name}: {clean_signature}", file=sys.stderr)

"""

def generate_cocci_rules(func: str) -> str:
    """Generate Coccinelle rules for a specific function"""
    return f"""
// ============================================================
// Rules for function: {func}
// ============================================================

// Rule 1: Remove static from function definitions with explicit return type
@remove_static_{func}_def@
type T;
identifier F = {func};
parameter list P;
@@
- static T F(P)
+ T F(P)
{{
  ...
}}

@script:python depends on remove_static_{func}_def@
T << remove_static_{func}_def.T;
F << remove_static_{func}_def.F;
P << remove_static_{func}_def.P;
@@
# Clean up parameter list
params = P
if ',' in params:
    param_list = [p.strip() for p in params.split(',')]
    params = ', '.join(param_list)

# Clean up type
type_str = T.strip()

# Extract and print signature
extract_and_print_signature(f"{{type_str}} {{F}}({{params}});", F)


// Rule 2: Remove static from function declarations with explicit return type
@remove_static_{func}_decl@
type T;
identifier F = {func};
parameter list P;
@@
- static T F(P);
+ T F(P);

@script:python depends on remove_static_{func}_decl@
T << remove_static_{func}_decl.T;
F << remove_static_{func}_decl.F;
P << remove_static_{func}_decl.P;
@@
# Clean up parameter list
params = P
if ',' in params:
    param_list = [p.strip() for p in params.split(',')]
    params = ', '.join(param_list)

# Clean up type
type_str = T.strip()

# Extract and print signature
extract_and_print_signature(f"{{type_str}} {{F}}({{params}});", F)

// Rule 3: Extract from non-static function definitions with explicit return type
@extract_{func}_def@
type T;
identifier F = {func};
parameter list P;
@@
T F(P)
{{
  ...
}}

@script:python depends on extract_{func}_def@
T << extract_{func}_def.T;
F << extract_{func}_def.F;
P << extract_{func}_def.P;
@@
# Clean up parameter list
params = P
if ',' in params:
    param_list = [p.strip() for p in params.split(',')]
    params = ', '.join(param_list)

# Clean up type
type_str = T.strip()

# Extract and print signature
extract_and_print_signature(f"{{type_str}} {{F}}({{params}});", F)

// Rule 4: Extract from non-static function declarations with explicit return type
@extract_{func}_decl@
type T;
identifier F = {func};
parameter list P;
@@
T F(P);

@script:python depends on extract_{func}_decl@
T << extract_{func}_decl.T;
F << extract_{func}_decl.F;
P << extract_{func}_decl.P;
@@
# Clean up parameter list
params = P
if ',' in params:
    param_list = [p.strip() for p in params.split(',')]
    params = ', '.join(param_list)

# Clean up type
type_str = T.strip()

# Extract and print signature
extract_and_print_signature(f"{{type_str}} {{F}}({{params}});", F)
"""

def generate_cocci_script(target_functions):
    """Generate complete Coccinelle script"""
    lines = [generate_header()]
    
    # Generate rules for each function
    for i, func in enumerate(target_functions):
        if func in ("NULL", "0"):
            continue
        lines.append(generate_cocci_rules(func))
        if i < len(target_functions) - 1:
            lines.append("")
    
    return '\n'.join(lines)

def main():
    # Parse command line arguments
    if len(sys.argv) != 3:
        print("Usage: python3 2_4_extract_definition.py <json_file> <output_cocci>")
        print()
        print("Arguments:")
        print("  json_file    : JSON file containing function data (e.g., filled_parsing.json)")
        print("  output_cocci : Output Coccinelle script file (e.g., extract_decl.cocci)")
        print()
        print("Example:")
        print("  python3 2_4_extract_definition.py filled_parsing.json extract_decl.cocci")
        print()
        print("To run and extract declarations:")
        print("  spatch --sp-file extract_decl.cocci --dir ../ 2>/dev/null > declarations.txt")
        print("  (or with --in-place to modify files)")
        print("  spatch --sp-file extract_decl.cocci --dir ../ --in-place 2>/dev/null > declarations.txt")
        sys.exit(1)
    
    json_file = sys.argv[1]
    output_cocci = sys.argv[2]
    
    # Check if input files exist
    if not os.path.exists(json_file):
        print(f"Error: JSON file not found: {json_file}", file=sys.stderr)
        sys.exit(1)
    
    # Load data
    print(f"Loading target functions from {json_file}...", file=sys.stderr)
    target_functions = load_target_functions(json_file)
    
    if not target_functions:
        print(f"Error: No valid functions found in {json_file}", file=sys.stderr)
        sys.exit(1)
    
    print(f"Found {len(target_functions)} unique target functions", file=sys.stderr)
    
    # Generate Coccinelle script
    print(f"Generating Coccinelle script with rules for {len(target_functions)} functions...", file=sys.stderr)
    cocci_script = generate_cocci_script(target_functions)
    
    # Write to output file
    with open(output_cocci, 'w', encoding='utf-8') as f:
        f.write(cocci_script)
    
    print(f"Coccinelle script written to {output_cocci}", file=sys.stderr)
    print(f"", file=sys.stderr)
    print(f"[SUCCESS] Script generation complete!", file=sys.stderr)
    print(f"", file=sys.stderr)
    print(f"To extract declarations only (no diff):", file=sys.stderr)
    print(f"  spatch --sp-file {output_cocci} --dir <source_dir> 2>/dev/null > declarations.txt", file=sys.stderr)
    print(f"", file=sys.stderr)
    print(f"To modify files AND extract declarations:", file=sys.stderr)
    print(f"  spatch --sp-file {output_cocci} --dir <source_dir> --in-place 2>/dev/null > declarations.txt", file=sys.stderr)

if __name__ == '__main__':
    main()