#!/usr/bin/env python3
"""
Function Pointer If-Else Chain Generator (Direct Comparison Version)
JSON 파일에서 함수 포인터 정보를 읽어 == 비교 방식의 if-else 체인 코드를 생성
"""

import json
import sys
import argparse
from pathlib import Path
from typing import Dict, List, Optional

class IfElseGenerator:
    def __init__(self, json_file: str):
        self.json_file = json_file
        self.data: List[Dict] = []
        
    def load_json(self):
        """JSON 파일 로드"""
        with open(self.json_file, 'r') as f:
            self.data = json.load(f)
        print(f"Loaded {len(self.data)} function pointer entries")
    
    def find_function(self, fp_name: str) -> Dict:
        """특정 함수 포인터 찾기"""
        for entry in self.data:
            if entry.get('fp_name') == fp_name:
                return entry
        return None
    
    def generate_if_else_chain(
        self, 
        fp_name: str, 
        variable: str = "",
        prefix: str = "",
        postfix: str = "",
        indent: int = 4
    ) -> str:
        """
        if-else 체인 생성 (== 비교 방식)
        
        Args:
            fp_name: 함수 포인터 이름
            variable: signature 앞에 붙을 변수 (예: "ctrl_netio->abort->")
            prefix: 함수 호출 앞에 붙을 문자열
            postfix: 함수 호출 뒤에 붙을 문자열
            indent: 들여쓰기 공백 수
        """
        entry = self.find_function(fp_name)
        
        if not entry:
            raise ValueError(f"Function pointer '{fp_name}' not found in JSON")
        
        assigned_fns = entry.get('assigned_fn', [])
        
        if not assigned_fns:
            raise ValueError(f"No assigned functions found for '{fp_name}'")
        
        # 들여쓰기 문자열
        indent_str = ' ' * indent
        
        # 코드 생성
        lines = []
        
        for i, core in enumerate(assigned_fns):
            # "0" 건너뛰기
            if core == "0":
                continue
            
            # signature 이름: {fp_name}_{core}
            signature_name = f"{fp_name}_{core}"
            
            # 첫 번째는 if, 나머지는 else if
            if i == 0 or (i == 1 and assigned_fns[0] == "0"):
                lines.append(
                    f"if ({variable}{fp_name}_signature == {signature_name}) {{"
                )
            else:
                lines.append(
                    f"else if ({variable}{fp_name}_signature == {signature_name}) {{"
                )
            
            # 함수 호출 생성
            call = f"{prefix}{core}{postfix}"
            lines.append(f"{indent_str}{call}")
            
            lines.append("}")
        
        return '\n'.join(lines)
    
    def generate_multiple(
        self, 
        fp_names: List[str], 
        variable: str = "",
        prefix: str = "",
        postfix: str = "",
        indent: int = 4
    ) -> Dict[str, str]:
        """여러 함수 포인터에 대한 if-else 체인 생성"""
        results = {}
        
        for fp_name in fp_names:
            try:
                code = self.generate_if_else_chain(
                    fp_name, variable, prefix, postfix, indent
                )
                results[fp_name] = code
            except ValueError as e:
                print(f"Error: {e}")
                results[fp_name] = None
        
        return results
    
    def print_code(
        self, 
        fp_name: str, 
        variable: str = "",
        prefix: str = "",
        postfix: str = "",
        indent: int = 4
    ):
        """생성된 코드 출력"""
        print(f"\n// Generated if-else chain for {fp_name}")
        print("="*70)
        code = self.generate_if_else_chain(fp_name, variable, prefix, postfix, indent)
        print(code)
        print("="*70)
    
    def save_to_file(
        self, 
        fp_names: List[str], 
        output_file: str, 
        variable: str = "",
        prefix: str = "",
        postfix: str = "",
        indent: int = 4
    ):
        """생성된 코드를 파일로 저장"""
        with open(output_file, 'w') as f:
            f.write("// Auto-generated if-else chains\n")
            f.write("// Generated by create_if_else.py\n")
            if variable:
                f.write(f"// Variable prefix: {variable}\n")
            if prefix:
                f.write(f"// Function prefix: {prefix}\n")
            if postfix:
                f.write(f"// Function postfix: {postfix}\n")
            f.write("\n")
            
            for fp_name in fp_names:
                try:
                    f.write(f"// {fp_name}\n")
                    code = self.generate_if_else_chain(
                        fp_name, variable, prefix, postfix, indent
                    )
                    f.write(code)
                    f.write("\n\n")
                except ValueError as e:
                    f.write(f"// Error: {e}\n\n")
        
        print(f"\nCode saved to: {output_file}")


def main():
    parser = argparse.ArgumentParser(
        description='Generate if-else chains with direct comparison (==) from JSON function pointer data',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  # Basic usage
  python create_if_else.py merged.json abort
  
  # With variable prefix
  python create_if_else.py merged.json abort --variable "ctrl_netio->abort->"
  
  # With function postfix
  python create_if_else.py merged.json abort --variable "ctrl_netio->abort->" --postfix "(nstrm);"
  
  # Complete example
  python create_if_else.py merged.json abort \\
      --variable "ctrl_netio->abort->" --prefix "" --postfix "(nstrm);" -o output.c
  
  # Multiple functions
  python create_if_else.py merged.json abort read write \\
      --variable "ctrl_netio->abort->" --postfix "(nstrm);" -o output.c

Output Format:
  if ({variable}{fp}_signature == {fp}_{core}) {{
      {prefix}{core}{postfix}
  }}

JSON Format Expected:
[
  {
    "fp_name": "abort",
    "assigned_fn": ["0", "core_netio_abort_cb", "tls_netio_abort_cb"]
  }
]

Note: "0" entries are automatically skipped.
        '''
    )
    
    parser.add_argument('json_file',
                       help='Path to JSON file containing function pointer data')
    parser.add_argument('fp_names',
                       nargs='+',
                       help='Function pointer name(s) to generate code for')
    parser.add_argument('--variable',
                       default='',
                       help='Variable prefix for signature (e.g., "ctrl_netio->abort->")')
    parser.add_argument('--prefix',
                       default='',
                       help='Prefix before function call (e.g., "result = ")')
    parser.add_argument('--postfix',
                       default='',
                       help='Postfix after function name (e.g., "(nstrm);")')
    parser.add_argument('-o', '--output',
                       help='Output file (default: print to stdout)')
    parser.add_argument('--indent',
                       type=int,
                       default=4,
                       help='Indentation spaces (default: 4)')
    
    args = parser.parse_args()
    
    # 입력 검증
    if not Path(args.json_file).exists():
        print(f"Error: JSON file '{args.json_file}' not found")
        sys.exit(1)
    
    # 생성기 초기화
    generator = IfElseGenerator(args.json_file)
    generator.load_json()
    
    # 코드 생성
    if args.output:
        # 파일로 저장
        generator.save_to_file(
            args.fp_names, 
            args.output, 
            args.variable,
            args.prefix,
            args.postfix,
            args.indent
        )
    else:
        # 화면에 출력
        for fp_name in args.fp_names:
            try:
                generator.print_code(
                    fp_name, 
                    args.variable,
                    args.prefix,
                    args.postfix,
                    args.indent
                )
            except ValueError as e:
                print(f"\nError: {e}")


if __name__ == "__main__":
    main()